version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: sqldb
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: crmdb
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: web
    #command: gunicorn dcrm.wsgi:application --bind 0.0.0.0:8000
    #command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && gunicorn dcrm.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/dcrm
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=crmdb
      - DB_USER=root
      - DB_PASSWORD=admin123
      - DB_HOST=db
      - DB_PORT=3306

volumes:
  mysql_data:
